### ISSUE TITLE
Typescript Declarations? 

### ISSUE THREAD

**Issue by Aryan6290** [GeorgeHop/react-native-country-codes-picker#1]
Could not find a declaration file for module 'react-native-country-codes-picker/components/CountryPicker'.

**Comment by kinjal34** [comment]
same with me,

error: Error: Unable to resolve module react-native-country-codes-picker/components/CountryPicker from

**Comment by kinjal34** [comment]
![Screenshot 2021-11-03 at 3 16 40 PM](https://user-images.githubusercontent.com/86356067/140038667-75b64eb8-de31-48f5-a363-ca2e1b7ced34.png)

**Comment by GeorgeHop** [comment]
Hello @kinjal34 ! Good to see you here ! Can you describe please which one version of lib. do you use ?

**Comment by GeorgeHop** [comment]
Try update to version 1.3.2. and we will see maybe it will fix the issue.

**Comment by kinjal34** [comment]
@GeorgeHop thanks for reply,

but still getting same error with this version!!

_version: react-native-country-codes-picker@1.3.2_


**error which I am getting,**

error: Error: Unable to resolve module react-native-country-codes-picker/components/CountryPicker from /Users/kinjal/Documents/Rn/accelevents/acceleventsapp/src/screens/DashBoardScreen/index.js: react-native-country-codes-picker/components/CountryPicker could not be found within the project or in these directories:
  node_modules
  ../node_modules
  ../../../../node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  47 | import getEventFeedContext from "../../Component/getEventFeedContext";
  48 | import WelcomeVideo from "../../Component/WelcomeVideo";
> 49 | import {CountryPicker} from "react-native-country-codes-picker/components/CountryPicker";
     |                              ^
  50 |
  51 |
  52 | const feedClientforAuth = getFeedContext();

**Comment by Aryan6290** [comment]
I was asking for Typescript declarations like this :
![image](https://user-images.githubusercontent.com/55250734/140757479-ea05f858-680b-44c5-b1ed-10e0f4405f8b.png)

**Comment by Aryan6290** [comment]
Its not actually an issue but a feature I wish to see in upcoming versions

**Comment by GeorgeHop** [comment]
@Aryan6290 for sure I will try to add TS declaration in the next version.
If you want you can add it by yourself, I will check if everything is clear and merge it. 
If not you should wait a little bit.

**Comment by GeorgeHop** [comment]
@kinjal34 have you tried steps from error ? 
Also do you use expo or pure react-native ?

**Comment by GeorgeHop** [comment]
@kinjal34 
I have tested it on brand new app. using this steps.
1. Created new app using expo init(expo version 43).
2. Installed package using yarn add.
3. And reproduce the basic sample from docs.

App.js

```JS
import React from 'react';
import {Text, View, StyleSheet, TouchableOpacity, Platform} from 'react-native';
import CountryPicker from "react-native-country-codes-picker";

export default function App() {
    const [show, setShow] = React.useState(false);
    const [countryCode, setCountryCode] = React.useState('');

    return (
        <View style={styles.container}>
            <TouchableOpacity onPress={() => setShow(true)}>
                <Text>
                    Test button
                </Text>
            </TouchableOpacity>
            <CountryPicker
                show={show}
                // when picker button press you will get the country object with dial code
                pickerButtonOnPress={(item) => {
                    setCountryCode(item.dial_code);
                    setShow(false);
                }}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 20,
        backgroundColor: '#ecf0f1',
        padding: 8,
    },
});
```

packaje.json
```JS
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^43.0.0",
    "expo-calendar": "~10.0.3",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-43.tar.gz",
    "react-native-country-codes-picker": "^1.3.2",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

**Comment by Aryan6290** [comment]
> @Aryan6290 for sure I will try to add TS declaration in the next version. If you want you can add it by yourself, I will check if everything is clear and merge it. If not you should wait a little bit.

sure I will try to make it <3

**Comment by GeorgeHop** [comment]
@Aryan6290 it would be great man !
@kinjal34 any new info about the issue ?

**Comment by kinjal34** [comment]
@GeorgeHop 
now issue in this index file

njal/Documents/Rn/accelevents/acceleventsapp/node_modules/react-native-country-codes-picker/index.js: 

None of these files exist:
  * node_modules/react-native-country-codes-picker/components/CountryPicker(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-country-codes-picker/components/CountryPicker/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | export default from "./components/CountryPicker";


![Screenshot 2021-11-09 at 3 00 59 PM](https://user-images.githubusercontent.com/86356067/140898649-1a0fef38-5719-44c8-9b6e-d831c43faa8c.png)

    |                      ^

**Comment by GeorgeHop** [comment]
@kinjal34 Please provide more info.
1. What do you use expo or pure react-native ? 
2. Can you provide source code ? 
3. Can you show your package.json ? 
4. Have you tried steps from the error ? 

Without all required info I can't help you.

> @GeorgeHop thanks for reply,
> 
> but still getting same error with this version!!
> 
> _version: react-native-country-codes-picker@1.3.2_
> 
> **error which I am getting,**
> 
> error: Error: Unable to resolve module react-native-country-codes-picker/components/CountryPicker from /Users/kinjal/Documents/Rn/accelevents/acceleventsapp/src/screens/DashBoardScreen/index.js: react-native-country-codes-picker/components/CountryPicker could not be found within the project or in these directories: node_modules ../node_modules ../../../../node_modules
> 
> If you are sure the module exists, try these steps:
> 
> 1. Clear watchman watches: watchman watch-del-all
> 2. Delete node_modules and run yarn install
> 3. Reset Metro's cache: yarn start --reset-cache
> 4. Remove the cache: rm -rf /tmp/metro-*
>    47 | import getEventFeedContext from "../../Component/getEventFeedContext";
>    48 | import WelcomeVideo from "../../Component/WelcomeVideo";
> 
> > 49 | import {CountryPicker} from "react-native-country-codes-picker/components/CountryPicker";
> > |                              ^
> > 50 |
> > 51 |
> > 52 | const feedClientforAuth = getFeedContext();

**Comment by kinjal34** [comment]
@GeorgeHop 
Its pure react native,
and I am using simple steps as mention in lid,

![Screenshot 2021-11-09 at 6 13 18 PM](https://user-images.githubusercontent.com/86356067/140926358-67b7a7a0-deb5-405d-95a5-18d614384f46.png)

**Comment by ramisalem** [comment]
Same issue here

**Comment by kinjal34** [comment]
@ramisalem 
I recommend this one,
https://www.npmjs.com/package/react-native-phone-number-input

**Comment by GeorgeHop** [comment]
Guys check your config please! Check comment in this issue it should help to you: 
https://github.com/GeorgeHop/react-native-screens-swiper/issues/2#issuecomment-969183567

**Comment by zeeshan112233** [comment]
Still facing the same issue
