### ISSUE TITLE
Unable to resolve module ./components/CountryPicker

### ISSUE THREAD

**Issue by ElChawich** [GeorgeHop/react-native-country-codes-picker#13]
After installing the library and opening the app i got this error on app startup
after checking the files i found that CountryPicker and CountryButton are in jsx format which is not supported, changing the formats to JS or TS fixes it
RN version: 0.68.1
![simulator_screenshot_95828E37-FA5F-4C7E-961E-9F56A0F9262B](https://user-images.githubusercontent.com/55316641/170227587-37ddff97-9d35-4fbb-8c5b-e05adad31c1a.png)
p

**Comment by saim11-cloud** [comment]
@ElChawich did u fix it? coz i also got the same error.

**Comment by ElChawich** [comment]
@saim11-cloud the fix is to change the extension of the 2 files in components folder from .jsx to .js... i created a pull request for it but it hasn't been approved yet

**Comment by saim11-cloud** [comment]
thanks @ElChawich but i found another library 'https://www.npmjs.com/package/rn-country-code-picker'. it worked perfectly fine.

**Comment by GeorgeHop** [comment]
Ahaha) Nice, someone stole my library
