### ISSUE TITLE
React native web support

### ISSUE THREAD

**Issue by MnParel** [GeorgeHop/react-native-country-codes-picker#15]
Hi,

Thanks for the library. is it supported in rn-web?

**Comment by GeorgeHop** [comment]
Currently no, but if you can provide functionality like that it will be great.

**Comment by GeorgeHop** [comment]
Also question about how it will looks like from the UI/UX.  So if you interested, feel free to create this chages and make a PR.

**Comment by Sheharyar566** [comment]
Added web support

![Capture](https://user-images.githubusercontent.com/29799626/180631307-615de541-1143-49f9-9b85-8bd120194c81.PNG)

**Comment by GeorgeHop** [comment]
@Sheharyar566 Thank you man! Alredy merged and and published new version check 1.4.2!
