### ISSUE TITLE
Please update the import code in guide

### ISSUE THREAD

**Issue by zuraizzafar** [GeorgeHop/react-native-country-codes-picker#21]
The code in guide:
`import {CountryPicker} from "react-native-country-codes-picker";`
is unable to import the library component onto the required screen. Because the component is exported by default, I used,
`import CountryPicker from "react-native-country-codes-picker";`
and it worked. I think updating the library will help others, Thank you.

**Comment by GeorgeHop** [comment]
Hi! Okay, thanks, changing docs)
