### ISSUE TITLE
Issue with lint

### ISSUE THREAD

**Issue by umangloria** [GeorgeHop/react-native-country-codes-picker#22]
Getting this error:
`node_modules/react-native-country-codes-picker/index.tsx(16,33): error TS7016: Could not find a declaration file for module './helpers/useKeyboardStatus'. '/Users/../../node_modules/react-native-country-codes-picker/helpers/useKeyboardStatus.js' implicitly has an 'any' type.`

Not sure how to fix it! Can anyone help with this?

**Comment by GeorgeHop** [comment]
Hi! Hmmm checking

**Comment by umangloria** [comment]
> Hi! Hmmm checking

Thanks, Let me know if you need any additional information from my side, This happens when we perform `yarn run lint && yarn run check-typescript`

**Comment by GeorgeHop** [comment]
Please check version 2.0.2 it might be because this useKeyboardStatus hook was not refactored to TS.

**Comment by umangloria** [comment]
Got another error which is straightforward to fix, Opened PR, feel free to discard PR as well. :) 
And Thank you for the fixing the issue swiftly.

https://github.com/GeorgeHop/react-native-country-codes-picker/pull/23

**Comment by umangloria** [comment]
Just let me know once you release a new version so I can update the version on my side and close this issue.

**Comment by GeorgeHop** [comment]
Published fix

**Comment by umangloria** [comment]
Amazing thank you so much.
