### ISSUE TITLE
Search input should accept country names ignoring letter accents.

### ISSUE THREAD

**Issue by algarcia-vector** [GeorgeHop/react-native-country-codes-picker#27]
I was searching for mexico, but I could not see any result. So, the thing is that I need to search it exactly like ''méxico'' with the ''é'' being accented.

I think it would be nice if we can ignore the accents on the search query for a better user experience.

I fixed this issue by modifying the next lines 119 and 122 in index.tsx 

    const resultCountries = React.useMemo(() => {
        const lowerSearchValue = searchValue.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");

        return codes.filter((country) => {
            if (country?.dial_code.includes(searchValue) || country?.name[lang || 'en'].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").includes(lowerSearchValue)) {
                return country;
            }
        });
    }, [searchValue]);

I needed to add **.normalize("NFD").replace(/[\u0300-\u036f]/g, "")** to ignore all accents in search query. 

Could this solution be added in the main branch?

**Comment by GeorgeHop** [comment]
HI! Yes I will try to add it in new update.

**Comment by GeorgeHop** [comment]
Ready! Checkout version 2.2.0

**Comment by algarcia-vector** [comment]
Awsome! is version 2.2.0 available now?
