### ISSUE TITLE
Background color is still white on dark mode

### ISSUE THREAD

**Issue by namluu25** [GeorgeHop/react-native-country-codes-picker#30]
I found a problem that on light mode, the background color is white and text is dark. But when switch to dark mode, background color is still white but text color is change to white. Great work, thank you so much!

**Comment by GeorgeHop** [comment]
Hello! You change the styles of modal when toggle dark mode? And can you provie some sample code?

**Comment by namluu25** [comment]
> Hello! You change the styles of modal when toggle dark mode? And can you provide some sample code?

Hi, sorry for late reply, I was busy lately. I haven't use any of styles, just plain FC.
Here is my code
```
<CountryPicker
        show={show}
        pickerButtonOnPress={pickerConfig}
        lang={'en'}
        enableModalAvoiding
        onBackdropPress={closePickerModal}
      />
```

https://imgur.com/a/hlyL5Hu I have a screenshot of dark/light mode right here

**Comment by GeorgeHop** [comment]
How I understand it's on android? Basicaly lib. doesn't support auto changing theme by your device theme. You should add theme specific styles yo want for each theme. Check this section: https://github.com/GeorgeHop/react-native-country-codes-picker#styling

**Comment by GeorgeHop** [comment]
You can remove all styles by yourself using section I sent.

**Comment by namluu25** [comment]
@GeorgeHop hi, I've been digging around your library and I found out that you have set the wrong style type for some props.

```
export interface Style {
    backdrop?: ViewStyle,
    modal?: ViewStyle,
    line?: ViewStyle,
    searchMessageText?: ViewStyle,
    itemsList?: ViewStyle,
    modalInner?: ViewStyle,
    countryMessageContainer?: ViewStyle,
    textInput?: ViewStyle,
    countryButtonStyles?: ViewStyle,
    flag?: ViewStyle,
    dialCode?: ViewStyle,
    countryName?: ViewStyle
}
```

From your README, you specify that ```// Styles for input [TextInput]```,  ```// Styles for search message [Text]```, ```// Dial code styles [Text]```. But you set it as ViewStyle instead of TextStyle, so I can't change the text color. Can you update the library?

And in 2.2.2 version, the modal show full the screen, so I can't see the search bar. https://imgur.com/a/QKocblG

**Comment by GeorgeHop** [comment]
Hmmm okay! I will update them soon

**Comment by GeorgeHop** [comment]
Look @namluu25 I little bit busy last time. May you prepare a PR? Because I will be able to fix it on the next week probably.
