### ISSUE TITLE
enableModalAvoiding with "Modal Height" not Working

### ISSUE THREAD

**Issue by xpario** [GeorgeHop/react-native-country-codes-picker#31]
when enableModalAvoiding={true} and you specify the "height" property in the Modal style, the keyboard avoiding view stops working. If you remove the "height" value (from below) it starts working again.

style={{
  modal: {
      height: 250,
  },
}}

**Comment by GeorgeHop** [comment]
Hi! Hmm strange... I will check it. And please send me sample code.

**Comment by GeorgeHop** [comment]
Check version 2.2.2

**Comment by virenradadiya** [comment]
I am still having the same issue. I am using the v2.3.5. Is there any solution?
