### ISSUE TITLE
missing placeholderTextColor

### ISSUE THREAD

**Issue by ingmiki** [GeorgeHop/react-native-country-codes-picker#32]
Hi, in React Native ver. > 0.69.0 it is necessary to specify the **placeholderTextColor** field in the **TextInput** component, only in this way the placeholder will be visible. Thanks a lot.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/102720784/204611912-e9127c06-f1a9-4325-8598-1ddc6f58505c.png">

**Comment by GeorgeHop** [comment]
Hello) You can use all TextInput props in CountryPicker look example. 

```JS 
 <CountryPicker
      show={show}
      pickerButtonOnPress={country => console.log(country)}
      lang={'en'}
      placeholderTextColor={'red'}
  />
```

**Comment by ingmiki** [comment]
Tanks a lot, I'v tried and It works for me! Bye Bye
