### ISSUE TITLE
A feature that allows certain countries to be displayed on top

### ISSUE THREAD

**Issue by karimcambridge** [GeorgeHop/react-native-country-codes-picker#36]
- Most other country pickers have this.

E.G, a prop that lets you enter US, CA, UK, and those 3 countries show at the top of the list.

**Comment by GeorgeHop** [comment]
Hi! Thank you for using our lib. good idea! Probably we can use ListHeaderComponent of FlatList for this feature!
To allow other devs to select country they want, better I think to allow to pass custom renderComponent to ListHeaderComponent which will return selected countries by developer. 

```JS

ListHeaderComponent={renderHeaderComponentProp(topCountriesToShowProp)}

```

If you able to add this it will be nice I will check and merge your PR as fast as I can! I other case you should wait some time when I will have free time to add this feature! Thank you!

**Comment by GeorgeHop** [comment]
Ready! Preparing new update

**Comment by GeorgeHop** [comment]
Check version 2.3.0 and docs for sure to properly use everything)

**Comment by karimcambridge** [comment]
Awesome. One last issue

`CountryButton` isn't exported, so recreating the default button might be effy?

**Comment by karimcambridge** [comment]
Okay, it's fine actually. I achieved the functionality I wanted through this.


```js
import React from 'react';
import { View } from 'react-native';
import { CountryButton } from 'react-native-country-codes-picker/components/CountryButton';

const CountryPickerHeader = ({countries, locale}) => (
	<View>
		{countries?.map((country, index) => {
			return (
				<CountryButton key={index} item={country} name={country?.name?.[locale || 'en']}/>
			);
		})}
	</View>
);

export default CountryPickerHeader;
```

THANK YOU!

**Comment by GeorgeHop** [comment]
Probably I also forgot to add onPress to example. All other things will be fixed soon, or if you have any chance to make an PR welcome!

**Comment by patrickdelfim** [comment]
Hi, the lib is great. But there is a problem with this functionality. We should send the onPress event to the `ListHeaderComponent`. I added this `ListHeaderComponent` just like in the example and realized the press event was not working and there is no way to access it from the inner `ListHeaderComponent`

**Comment by GeorgeHop** [comment]
Hmm probably onPress missing inside ListHeadeComponent... Need to check
