### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Overdash** [GeorgeHop/react-native-country-codes-picker#41]
Just some minor suggestions (I can make a PR for this if needed):

1. Export the `types` and `CountryButton` Component at top level (in index.ts). Makes it easier to use the library
2. Correctly type `ListHeaderComponent` with `({countries: CountryItem[], locale: string}) => JSX.Element` To avoid TS false-errors when using the library.

**Comment by GeorgeHop** [comment]
Hi! thank you for using our lib. if you need this changes to be fixed fast then probably you should make PR. In other cases I will add it and publish in two weeks.
