### ISSUE TITLE
Add correct types for Styles and ListHeaderComponent

### ISSUE THREAD

**Issue by Bjorgar** [GeorgeHop/react-native-country-codes-picker#42]
Hi! I found some incorrect types for `Style` type and `ListHeaderComponent`.
This is my solutions:
1.
![image](https://user-images.githubusercontent.com/36771325/225585826-8b940e15-56b6-4795-81cf-16c8950d5a95.png)
2.
![image](https://user-images.githubusercontent.com/36771325/225585887-6ae4118a-c63a-46df-868e-8bacea3206c7.png)

**Comment by GeorgeHop** [comment]
Checked and merged! Thank you!
