### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by kasperkberg** [GeorgeHop/react-native-country-codes-picker#49]
Hi,
Thanks for the work! Very much appreciated!

I created a pull request to only show popular countries if there is no searchValue. As long as the popular countries doesn't filter when searching, I would prefer them to go away. Possible to merge that (if it looks ok), and update the package with the types-fixes done 3 weeks ago as well?

**Comment by GeorgeHop** [comment]
Updating and merged all your stuff

**Comment by GeorgeHop** [comment]
The architecture of component looks like that... First we open Modal component of react native and then trigger onShow event which open inner component with animations and other stuff.

**Comment by GeorgeHop** [comment]
So the delay is related probably to the bridge and the native side. Another case you can try is animate the inner component using useEffect when show state changes, maybe it will be faster but amination may work in a different way in that case.
