### ISSUE TITLE
Handle Back button press

### ISSUE THREAD

**Issue by remi2257** [GeorgeHop/react-native-country-codes-picker#59]
## Description
When the back button is pressed, nothing happen which feels like the application is buggy.

## Problem
When a Modal is opened, BackButton events are not propagated. As this component is using a Modal, developers cannot catch this event

## Solution
Close the modal when the back button is pressed

```
import { BackHandler } from "react-native";

// Add handleBackButton to props

useEffect(() => {
  let backHandler: NativeEventSubscription;
  if (handleBackButton) {
    backHandler = BackHandler.addEventListener("hardwareBackPress", () => {
      closeModal();
    });
  }

  return () => {
    backHandler?.remove();
  };
}, [handleBackButton]);
```

**Comment by remi2257** [comment]
By the way, thanks for the great work.

Country picking is such an important thing but there is no other library that provide the customization options that you provided, I'm glad that I find this library !

**Comment by GeorgeHop** [comment]
Thank you!) Have you tried onRequestClose prop? Check the docs, maybe it will help you?!

**Comment by remi2257** [comment]
Ooh, yes, that's it !
I didn't see it on the README, I thought it was a function used internally by the library

Thanks a lot ;)
