### ISSUE TITLE
Want to Customize the flag 

### ISSUE THREAD

**Issue by Nikhil-Rattan** [GeorgeHop/react-native-country-codes-picker#61]
I want to customize the flag and want to make it circular, but though I'm receiving flag in Text Component, so I'm no able to customize it

**Comment by GeorgeHop** [comment]
Hello! Have you tried this prop described in the docs ```itemTemplate```? It will work as renderItem for each element, probably you will be able to customize it how you want.

Flag it's a text so you should wrap it in Text component but you can use View around Text component to add some circular container.

**Comment by GeorgeHop** [comment]
Hello! Have you tried this prop described in the docs ```itemTemplate```? It will work as renderItem for each element, probably you will be able to customize it how you want.

Flag it's a text so you should wrap it in Text component but you can use View around Text component to add some circular container.

**Comment by GeorgeHop** [comment]
In case you wanna make flags circular you can try to increase font size) And put it in a circular View with overflow maybe it will help you.

**Comment by Nikhil-Rattan** [comment]
@GeorgeHop Thanks for the instant guidance and for such a brief and clear solution. I will try using itemTemplate and do let you know if I still faces some issue. Thanks once again!!
