### ISSUE TITLE
The translation for Turkey in French should be Turquie not dinde (which is the bird)

### ISSUE THREAD

**Issue by stuartrapop** [GeorgeHop/react-native-country-codes-picker#64]

**Comment by GeorgeHop** [comment]
Sorry, some of the translations may be incorrect) Most of names I trying to verify by myself... But it's very hard to verify all country names on all langs by one hand. If you native French speaker you can review all countries and make a PR to update those which wrong.

**Comment by stuartrapop** [comment]
Will do in the next days. Thanks for the quality package.

**Comment by AlixH** [comment]
Up
