### ISSUE TITLE
Element type is invalid: expected a string(for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by Anan7Codes** [GeorgeHop/react-native-country-codes-picker#7]
Hey I'm get this "Element type is invalid: expected a string(for built-in components) or a class/function (for composite components) but got: undefined." error. I've literally just copy pasted the code from the demo. Any idea? Thanks for this package btw :D

**Comment by GeorgeHop** [comment]
Probably here is the fix: https://github.com/GeorgeHop/react-native-country-codes-picker/pull/6

**Comment by GeorgeHop** [comment]
Please try v1.3.4, issue should be fixed there

**Comment by Anan7Codes** [comment]
Still facing the same error :(

**Comment by GeorgeHop** [comment]
Okay I will check it shortly

**Comment by GeorgeHop** [comment]
Okay, I have checked last version 1.3.4 and no error exist there. Can you give miniumal reproducable example? Also provide your package.json please, and screenshot of code where you call picker.

**Comment by Anan7Codes** [comment]
So I'll just post my component code and package.json below.

`import React, { useState } from 'react'
import { Text, SafeAreaView, Dimensions, ScrollView, TouchableOpacity, TextInput, View, Platform } from 'react-native';
import { FontAwesome5 } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import {CountryPicker} from "react-native-country-codes-picker";

const SCREEN_WIDTH = Dimensions.get('window').width


const PersonalDetailsScreen = () => {
    const navigation = useNavigation();

    const [ show, setShow ] = useState(false);
    const [ countryCode, setCountryCode ] = useState('');
    const [ male, setMale ] = useState(true)

    return (
        <SafeAreaView style={{alignItems: 'center', backgroundColor: '#fff', flex: 1, paddingTop: Platform.OS === 'ios' ? 0 : 30}}>
            <TouchableOpacity onPress={() => navigation.goBack()} style={{left: 20, width: SCREEN_WIDTH, marginBottom: 10}}>
                <Text style={{fontFamily: 'Manrope_400Regular'}}><FontAwesome5 name="arrow-left" size={14} color="#000"/> Back to Profile</Text>
            </TouchableOpacity>

            <ScrollView style={{backgroundColor: '#fafafa', width: SCREEN_WIDTH}} contentContainerStyle={{marginHorizontal: 15, paddingBottom: 100}}>
                <Text style={{fontFamily: 'JosefinSans_700Bold', fontSize: 30, marginTop: 20}}>Personal Details</Text>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 20, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fff', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>First Name:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold'}} placeholder='Enter First Name'/>
                </View>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fff', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>Last Name:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold'}} placeholder='Enter Last Name'/>
                </View>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fafafa', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>Email:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold', color: '#808080'}} value="*****@outlook.com" editable={false}/>
                </View>

                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15}}>
                    <TouchableOpacity onPress={() => setMale(true)} style={{flex: 1, alignItems: 'center', paddingVertical: 15, backgroundColor: male ? '#fff' : '#ebecf0', borderTopLeftRadius: 15, borderBottomLeftRadius: 15}}>
                        <Text style={{fontFamily: 'Manrope_600SemiBold', color: male ? '#0055b3' : '#bebebe', fontSize: 14}}>Male</Text>
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => setMale(false)} style={{flex: 1, alignItems: 'center', paddingVertical: 15, backgroundColor: !male ? '#fff' : '#ebecf0', borderTopRightRadius: 15, borderBottomRightRadius: 15}}>
                        <Text style={{fontFamily: 'Manrope_600SemiBold', color: !male ? '#0055b3' : '#bebebe', fontSize: 14}}>Female</Text>
                    </TouchableOpacity>
                </View>

                <View>
                <TouchableOpacity
                    onPress={() => setShow(true)}
                    style={{
                        width: '80%',
                        height: 60,
                        backgroundColor: 'black',
                        padding: 10,
                    }}
                >
                    <Text style={{
                        color: 'white',
                        fontSize: 20
                    }}>
                        {countryCode}
                    </Text>
                </TouchableOpacity>

                <CountryPicker
                    show={show}
                    pickerButtonOnPress={(item) => {
                        setCountryCode(item.dial_code);
                        setShow(false);
                    }}
                />
                </View>

            </ScrollView> 

        </SafeAreaView>
    )
}

export default PersonalDetailsScreen`

package.json

`{
  "name": "****",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/josefin-sans": "^0.2.0",
    "@expo-google-fonts/manrope": "^0.2.0",
    "@expo/vector-icons": "^12.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@gorhom/portal": "^1.0.12",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "expo": "~44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-country-region-selector": "^3.4.0",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-circular-progress-indicator": "^2.0.5",
    "react-native-country-codes-picker": "^1.3.4",
    "react-native-drop-shadow": "^0.0.4",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-shadow-2": "^6.0.0",
    "react-native-simple-animations": "^0.3.0",
    "react-native-svg": "12.1.1",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by Anan7Codes** [comment]
My code component

`import React, { useState } from 'react'
import { Text, SafeAreaView, Dimensions, ScrollView, TouchableOpacity, TextInput, View, Platform } from 'react-native';
import { FontAwesome5 } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import {CountryPicker} from "react-native-country-codes-picker";

const SCREEN_WIDTH = Dimensions.get('window').width


const PersonalDetailsScreen = () => {
    const navigation = useNavigation();

    const [ show, setShow ] = useState(false);
    const [ countryCode, setCountryCode ] = useState('');
    const [ male, setMale ] = useState(true)

    return (
        <SafeAreaView style={{alignItems: 'center', backgroundColor: '#fff', flex: 1, paddingTop: Platform.OS === 'ios' ? 0 : 30}}>
            <TouchableOpacity onPress={() => navigation.goBack()} style={{left: 20, width: SCREEN_WIDTH, marginBottom: 10}}>
                <Text style={{fontFamily: 'Manrope_400Regular'}}><FontAwesome5 name="arrow-left" size={14} color="#000"/> Back to Profile</Text>
            </TouchableOpacity>

            <ScrollView style={{backgroundColor: '#fafafa', width: SCREEN_WIDTH}} contentContainerStyle={{marginHorizontal: 15, paddingBottom: 100}}>
                <Text style={{fontFamily: 'JosefinSans_700Bold', fontSize: 30, marginTop: 20}}>Personal Details</Text>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 20, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fff', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>First Name:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold'}} placeholder='Enter First Name'/>
                </View>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fff', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>Last Name:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold'}} placeholder='Enter Last Name'/>
                </View>
                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15, paddingHorizontal: 10, paddingVertical: 15, backgroundColor: '#fafafa', borderColor: '#d3d3d3', borderWidth: 1, borderRadius: 5}}>
                    <Text style={{fontFamily: 'Manrope_600SemiBold', color: '#808080', marginRight: 10}}>Email:</Text>
                    <TextInput style={{flex: 1, fontFamily: 'Manrope_600SemiBold', color: '#808080'}} value="*****@outlook.com" editable={false}/>
                </View>

                <View style={{flexDirection: 'row', alignItems: 'center', marginTop: 15}}>
                    <TouchableOpacity onPress={() => setMale(true)} style={{flex: 1, alignItems: 'center', paddingVertical: 15, backgroundColor: male ? '#fff' : '#ebecf0', borderTopLeftRadius: 15, borderBottomLeftRadius: 15}}>
                        <Text style={{fontFamily: 'Manrope_600SemiBold', color: male ? '#0055b3' : '#bebebe', fontSize: 14}}>Male</Text>
                    </TouchableOpacity>
                    <TouchableOpacity onPress={() => setMale(false)} style={{flex: 1, alignItems: 'center', paddingVertical: 15, backgroundColor: !male ? '#fff' : '#ebecf0', borderTopRightRadius: 15, borderBottomRightRadius: 15}}>
                        <Text style={{fontFamily: 'Manrope_600SemiBold', color: !male ? '#0055b3' : '#bebebe', fontSize: 14}}>Female</Text>
                    </TouchableOpacity>
                </View>

                <View>
                <TouchableOpacity
                    onPress={() => setShow(true)}
                    style={{
                        width: '80%',
                        height: 60,
                        backgroundColor: 'black',
                        padding: 10,
                    }}
                >
                    <Text style={{
                        color: 'white',
                        fontSize: 20
                    }}>
                        {countryCode}
                    </Text>
                </TouchableOpacity>

                <CountryPicker
                    show={show}
                    pickerButtonOnPress={(item) => {
                        setCountryCode(item.dial_code);
                        setShow(false);
                    }}
                />
                </View>

            </ScrollView> 

        </SafeAreaView>
    )
}

export default PersonalDetailsScreen`

My package.json

`{
  "name": "****",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo-google-fonts/josefin-sans": "^0.2.0",
    "@expo-google-fonts/manrope": "^0.2.0",
    "@expo/vector-icons": "^12.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@gorhom/portal": "^1.0.12",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "expo": "~44.0.0",
    "expo-app-loading": "~1.3.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-country-region-selector": "^3.4.0",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-circular-progress-indicator": "^2.0.5",
    "react-native-country-codes-picker": "^1.3.4",
    "react-native-drop-shadow": "^0.0.4",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-shadow-2": "^6.0.0",
    "react-native-simple-animations": "^0.3.0",
    "react-native-svg": "12.1.1",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
`

**Comment by GeorgeHop** [comment]
Maybe your config doesn't understand files with .jsx prefixes.
You can try to check it by yourself just remove x from prefix in CountryPicker component and try to reload the app. 
If everything will be good you can make a PR.

**Comment by EnaRukavina** [comment]
`import CountryPicker from 'react-native-country-codes-picker'` fixed the issue for me
