### ISSUE TITLE
Flags doesnt shows on React Native Web (Windows)

### ISSUE THREAD

**Issue by AstrOOnauta** [GeorgeHop/react-native-country-codes-picker#71]
Unfortunately, flag emojis are not displayed on windows.
How can i fix it?

Print below:
![image](https://github.com/GeorgeHop/react-native-country-codes-picker/assets/81580470/af1ad9df-e2bf-4d75-bbf8-3f192e56e841)

**Comment by GeorgeHop** [comment]
Hi, this library was not very well tested on web. Maybe some issues with styles?

**Comment by AstrOOnauta** [comment]
Hey @GeorgeHop

I did a test usyng other `fontFamily` and work...its name is `TwemojiMozilla`!
For now, this worked for me...
