### ISSUE TITLE
how to show only the country flag and name?

### ISSUE THREAD

**Issue by rodrigodiasf1984** [GeorgeHop/react-native-country-codes-picker#85]
Hi, thanks for this package! 

@GeorgeHop how can I hide the countryCode? 

![image](https://github.com/GeorgeHop/react-native-country-codes-picker/assets/30758309/e934ce91-bd6f-4be2-93bd-ae89b40abddb)

thanks

**Comment by GeorgeHop** [comment]
Hello, you can create custom country button or hide country code using styles 😉

Check please styling section in docs ☺️

**Comment by rodrigodiasf1984** [comment]
Hello @GeorgeHop , thanks for your help!
![image](https://github.com/GeorgeHop/react-native-country-codes-picker/assets/30758309/999cd76e-1f2a-4c99-8c36-47e6b04c7403)
