### ISSUE TITLE
How to preselect a country

### ISSUE THREAD

**Issue by jorgtz** [GeorgeHop/react-native-country-codes-picker#9]
We are going to detect user's locale and based on that we need to populate the initial value of the Country Picker. Is there a way to do this?

**Comment by GeorgeHop** [comment]
Hi, and sorry if I late, probably we forgot to add initial Value or value field. You can add it by yourself and make a PR or I will add this props when I will be available.

**Comment by GeorgeHop** [comment]
So try this feature in new version of library 1.4.0
